ARG version 
FROM almalinux:${version:-9}
#FROM almalinux:9
ENV course="devops" \
    duration="120hrs"
ARG trainer="sivakumar"
RUN echo "Hi, Course is: ${course}, duration is: ${duration}, trainer is: ${trainer}"
CMD ["sleep", "1000"]
